# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Inspiration' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Inspiration
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionObjectDetection'
  pod 'Firebase/Database'
  pod 'Firebase/Analytics'

  target 'InspirationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InspirationUITests' do
    # Pods for testing
  end

end
